spring:
  profiles:
    include: "git"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/bhaveenopsmx/gitops-accounts.git"
          username: "bhaveenlatest"
          password: "6dbb03939c6eec6458874055b994503af14a8836"
encrypt:
  key: "Q7udUkHPuA3VnNlOtksSgQ"
